version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: langchain
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain

    ports:
      - "6024:5432"

    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
